export interface Track {
  title: string;
  artist: string;
  youtubeId: string;
}

export const tracks: Track[] = [
{ title: 'Chadti Jawani', artist: 'Sanober & The Masti Express', youtubeId: 'hxJ4mc-Lr4o' },
{ title: 'Mere Naseeb Mein (Remix)', artist: 'Baby H | Prem & Hardeep | Megha Chatterji', youtubeId: '04QVh47sJq4' },
{ title: 'Ucha Lamba Kad', artist: 'Welcome | Akshay Kumar, Katrina Kaif', youtubeId: 'qG4rvr7Iggc' },
{ title: 'Chudi', artist: 'Falguni Pathak', youtubeId: 'Xna3I11v9Vs' },
{ title: 'Sharara', artist: 'Mere Yaar Ki Shaadi Hai | Asha Bhosle', youtubeId: 'DUT0fG0KYPo' },
{ title: 'Kaliyon Ka Chaman', artist: 'Shashwati', youtubeId: '4bQSvSRrlCA' },
{ title: 'Beedi Jalaile', artist: 'Omkara | Sukhwinder Singh, Sunidhi Chauhan', youtubeId: 'XLJCtZK0x5M' },
{ title: 'Dil Mere', artist: 'The Local Train', youtubeId: 'qLCLvzTGFVM' },
{ title: 'Beete Lamhein', artist: 'KK', youtubeId: 'N-n8V7k_14I' },
{ title: 'Ektarfa', artist: 'King', youtubeId: '4IAnSQKUC5Q' },
{ title: 'Piya Ghar Aavenge', artist: 'Kailash Kher', youtubeId: 'zgJPTTiCK2E' },
{ title: 'Same Time Same Jagah', artist: 'Chaar Din | Sandeep Brar, Kulwinder Billa', youtubeId: 'HC172grgTwU' },
{ title: 'Afreen Afreen', artist: 'Rahat Fateh Ali Khan & Momina Mustehsan', youtubeId: 'kw4tT7SCmaY' },
{ title: 'Mishri', artist: 'Anuv Jain', youtubeId: '0P3Gt-60yLc' },
{ title: 'Kora Kagaz Tha Yeh Man Mera', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'IJgRm_NQs8A' },
{ title: 'Laavan', artist: 'Jasmine Sandlas | Mofusion', youtubeId: 'OxXKDGO-MYQ' },
{ title: 'Tera Zikr', artist: 'Darshan Raval', youtubeId: 'eK0IIyBlYew' },
{ title: 'Namak', artist: 'Omkara | Bipasha Basu & Saif Ali Khan', youtubeId: '5WB8ujhAK7c' },
{ title: 'Saiyan Ji Dilwa Mangele', artist: 'Sasura Bada Paisa Wala | Manoj Tiwari', youtubeId: 'iZAfR5HGwBY' },
{ title: 'Hai Junoon', artist: 'KK', youtubeId: '_hEgNwyHlAU' },
{ title: 'Video Games', artist: 'Lana Del Rey', youtubeId: 'cE6wxDqdOV0' },
{ title: 'Tere Sang Ishq Hua', artist: 'Arijit Singh & Neeti Mohan', youtubeId: '0qgMcrGuyQc' },
{ title: 'Kana Yaari', artist: 'Kaifi Khalil, Eva B & Wahab Bugti', youtubeId: '0oEsLkwE3g8' },
{ title: 'Mehrama', artist: 'Darshan Raval & Antara Mitra', youtubeId: 'HYUpNJJELeE' },
{ title: 'Pyar Deewana Hota Hai', artist: 'Kishore Kumar', youtubeId: 'WHd3NuhxrBM' },
{ title: 'Aankhon Mein Teri', artist: 'KK', youtubeId: 'tqmqB-4Xt9U' },
{ title: 'Do Dhaari Talwaar', artist: 'Mere Brother Ki Dulhan | Shweta Pandit, Shahid Mallya', youtubeId: 'm66aEQ3Ssdw' },
{ title: 'Maeri', artist: 'Euphoria', youtubeId: 'MGMh7kYzNqo' },
{ title: 'Aap Ki Aankhon Mein Kuch', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'K4vW8Y3636g' },
{ title: 'Aaqa', artist: 'Abida Parveen & Ali Sethi', youtubeId: 'LekqDjknArc' },
{ title: 'Bhar Do Jholi Meri', artist: 'Sabri Brothers', youtubeId: '55lmaGp_Uek' },
{ title: 'Tum Se Hi', artist: 'Mohit Chauhan', youtubeId: 'Cb6wuzOurPc' },
{ title: 'Achha Lagta Hain', artist: 'Aarakshan | Saif Ali Khan, Deepika | Mohit Chauhan, Shreya Ghoshal', youtubeId: 'wgzTfDqgNq8' },
{ title: 'Chhookar Mere Manko', artist: 'Kishore Kumar', youtubeId: 'BOLYNw3x1lE' },
{ title: 'Aa Re Pritam Pyaare', artist: 'Rowdy Rathore | Akshay Kumar | Mamta Sharma | Sajid Wajid', youtubeId: 'e3lgNmuajrg' },
{ title: 'Kasoor', artist: 'Prateek Kuhad', youtubeId: 'BmUe3-sfr7E' },
{ title: 'Riha', artist: 'Anuv Jain', youtubeId: 'oXKWFFefWK0' },
{ title: 'Gul', artist: 'Anuv Jain', youtubeId: 'SmaY7RfBgas' },
{ title: 'Dil Ibaadat', artist: 'KK', youtubeId: 'w8wZ9-2-a1M' },
{ title: 'Tum Hi Ho', artist: 'Arijit Singh', youtubeId: 'Umqb9KENgmk' },
{ title: 'Kamariya Dole Dole', artist: 'Neelkamal Singh, Shilpi Raj', youtubeId: 'w0Y6EsqnMbo' },
{ title: 'Chhaliya', artist: 'Tashan | Kareena Kapoor | Sunidhi Chauhan, Piyush Mishra | Vishal-Shekhar', youtubeId: 'AdC0Q2EhBbg' },
{ title: 'Choo Lo', artist: 'The Local Train', youtubeId: 'sFMRqxCexDk' },
{ title: 'Kabira (Encore)', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'jHNNMj5bNQw' },
{ title: 'Makaiya Me Raja Ji', artist: 'Darar | Pawan Singh, Monalisa', youtubeId: 'Maz5mEvtSj8' },
{ title: 'Tune Kaha', artist: 'Prateek Kuhad', youtubeId: 'miXdVbIm5BY' },
{ title: 'Kaho Na Kaho', artist: 'Amir Jamal', youtubeId: 'GPvCVzD70Zs' },
{ title: 'Khwab Dekhe', artist: 'Race | Monali Thakur, Neeraj Shridhar | Pritam', youtubeId: 'n_cBEbjWdio' },
{ title: 'Mahiye Jinna Sohna', artist: 'Darshan Raval', youtubeId: 'D1G_jrSSEe4' },
{ title: 'K.', artist: 'Cigarettes After Sex', youtubeId: 'L4sbDxRz29Q' },
{ title: 'Tu Mile Dil Khile', artist: 'Kumar Sanu', youtubeId: 'nqTS7ngviwQ' },
{ title: 'Soni Soni', artist: 'Darshan Raval, Jonita Gandhi & Rochak Kohli', youtubeId: 'y8vwzo8AgXU' },
{ title: 'Gulabi Aankhen', artist: 'Mohammad Rafi', youtubeId: '6Z3DO-OFIjQ' },
{ title: 'Zara Sa', artist: 'KK', youtubeId: 'h53N55_n-9M' },
{ title: 'Khudi', artist: 'The Local Train', youtubeId: '9LjKAt6SkdQ' },
{ title: 'Kya Hua Tera Wada', artist: 'Mohammad Rafi', youtubeId: 'W6dKaCV-mJQ' },
{ title: 'Ilahi', artist: 'Arijit Singh', youtubeId: '8T6b-h418uM' },
{ title: 'Subhanallah', artist: 'Sreerama Chandra & Shilpa Rao', youtubeId: 'QYO6AlxiRE4' },
{ title: 'Ocean', artist: 'Anuv Jain', youtubeId: 'RpHUIUslYv0' },
{ title: 'Latoo', artist: 'Ghajini | Shreya Ghoshal, A.R. Rahman', youtubeId: 'ORiC-DAahuM' },
{ title: 'Javeda Zindagi / Tose Naina Lage', artist: 'Kshitij Tarey & Shilpa Rao', youtubeId: 'wpka0Q8hlXc' },
{ title: 'Sajna Ve Sajna', artist: 'Chameli | Sunidhi Chauhan | Kareena Kapoor, Rahul Bose', youtubeId: 'yR5B-00peGQ' },
{ title: 'Maan Meri Jaan', artist: 'King', youtubeId: 'VuG7ge_8I2Y' },
{ title: 'Alag Aasmaan', artist: 'Anuv Jain', youtubeId: '8N362h-K-8g' },
{ title: 'Suraj Hua Maddham', artist: 'Sonu Nigam & Alka Yagnik', youtubeId: 'L0zKs8i7Nc8' },
{ title: 'KODAK', artist: 'King & Seedhe Maut', youtubeId: 'Ecs-foVS74Q' },
{ title: 'Kabhi Kabhie Mere Dil Mein', artist: 'Mukesh', youtubeId: 'BB6KvXQx090' },
{ title: 'Another Love', artist: 'Tom Odell', youtubeId: 'MwpMEbgC7DA' },
{ title: 'Pasoori', artist: 'Ali Sethi & Shae Gill', youtubeId: '5Eqb_-j3FDA' },
{ title: 'Aftab', artist: 'The Local Train', youtubeId: '8992_b1M_w8' },
{ title: 'Pala Satake', artist: 'Sarkar Raj | Pawan Singh, Monalisa', youtubeId: 'lxO7Trxqq_M' },
{ title: 'Chemtrails Over the Country Club', artist: 'Lana Del Rey', youtubeId: 'vBHild0PiTE' },
{ title: 'Liggi', artist: 'Ritviz', youtubeId: '6BYIKEH0RCQ' },
{ title: 'The Humma Song', artist: 'OK Jaanu | Shraddha Kapoor, Aditya Roy Kapur | A.R. Rahman, Badshah, Tanishk', youtubeId: '1tVL11ULjYY' },
{ title: 'Agar Tum Saath Ho', artist: 'Arijit Singh & Alka Yagnik', youtubeId: 'FOA9iyxsW_A' },
{ title: 'Brooklyn Baby', artist: 'Lana Del Rey', youtubeId: 'T5xcnjAG8pE' },
{ title: 'Hoth Rasiley', artist: 'Welcome | Malaika Arora | Nana Patekar, Anil Kapoor, Akshay Kumar', youtubeId: 'huWzhZrazTk' },
{ title: 'Rashke Qamar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'gY01irEl8Eo' },
{ title: 'Saiyyan', artist: 'Kailash Kher', youtubeId: 'TuUVVKVdZm4' },
{ title: 'Satranga', artist: 'Arijit Singh', youtubeId: 'HrnrqYxYrbk' },
{ title: 'Yellow', artist: 'Coldplay', youtubeId: 'yKNxeF4KMsY' },
{ title: 'Jalebi Bai', artist: 'Double Dhamaal | Mallika Sherawat', youtubeId: 'DUy7Kqh9HCY' },
{ title: 'O Re Piya', artist: 'Rahat Fateh Ali Khan', youtubeId: 'iv7lcUkFVSc' },
{ title: 'Tujhse Naraz Nahin Zindagi', artist: 'Lata Mangeshkar / Anup Ghoshal', youtubeId: 'K1qnkWTn56w' },
{ title: 'Dil Dooba', artist: 'Khakee | Sonu Nigam, Shreya Ghoshal | Aishwarya Rai, Akshaye Kumar', youtubeId: 'OWc7Utgx_Q4' },
{ title: 'O Meri Jaan', artist: 'KK', youtubeId: 'n1mqINz7g1w' },
{ title: 'Teri Deewani', artist: 'Kailash Kher', youtubeId: 'zZasH6qkn8M' },
{ title: 'Roop Tera Mastana', artist: 'Kishore Kumar', youtubeId: 'o7Jnp949e2Y' },
{ title: 'Saat Samundar Paar', artist: 'Vishwatma | Sunny Deol, Divya Bharti | Sadhana Sargam | Anand Bakshi', youtubeId: '7TManB-eG_g' },
{ title: 'Khwaja Mere Khwaja', artist: 'A.R. Rahman', youtubeId: 'z4RvWbJlbPU' },
{ title: 'Tera Mera Rishta', artist: 'Mustafa Zahid', youtubeId: 'XA_uBJjutgc' },
{ title: 'Iraaday', artist: 'Abdul Hannan & Rakan', youtubeId: 'o6c4_1-987M' },
{ title: 'Man Kunto Maula', artist: 'Javed Ali & Shadab Faridi', youtubeId: '-Dby8p6mZhY' },
{ title: 'Cinnamon Girl', artist: 'Lana Del Rey', youtubeId: 'Q4yR4_W1o2s' },
{ title: 'Main Aai Hoon U.P. Bihar Lootne', artist: 'Shool | Shilpa Shetty | Sapna Awasthi', youtubeId: 'etN8Pn-DK1U' },
{ title: 'Udd Gaye', artist: 'Ritviz', youtubeId: 'v2-9rIL_f4w' },
{ title: 'Tere Bina Zindagi Se', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: '8-HnmVg0-O8' },
{ title: 'Palang Sagwan Ke', artist: 'Doli Saja Ke Rakhna | Khesari Lal Yadav', youtubeId: 'DD6N7_S04FA' },
{ title: 'Pee Loon', artist: 'Mohit Chauhan', youtubeId: 'Z95W62S6q1I' },
{ title: 'Co2', artist: 'Prateek Kuhad', youtubeId: 'U2SVCCENLjE' },
{ title: 'Tu Hi Meri Shab Hai', artist: 'KK', youtubeId: 'cGNcjqXe87U' },
{ title: 'Rimjhim Gire Sawan', artist: 'Kishore Kumar / Lata Mangeshkar', youtubeId: 'JQoSSJDZxOo' },
{ title: 'Kuch Is Tarah', artist: 'Atif Aslam', youtubeId: 'E74V-X9AtAg' },
{ title: 'Heeriye', artist: 'Jasleen Royal & Arijit Singh', youtubeId: 'RLzC55ai0eo' },
{ title: 'Raanjhanaa', artist: 'A.R. Rahman & Jaswinder Singh', youtubeId: 'l8zZ-8c2U3g' },
{ title: 'Tumse Milke Dil ka Jo Haal Kiya', artist: 'Main Hoon Na | Shahrukh Khan, Sushmita Sen', youtubeId: 'd_zaA4Dyc3Y' },
{ title: 'Tu Jhoom', artist: 'Naseebo Lal & Abida Parveen', youtubeId: '7D4vNcK6D38' },
{ title: 'Zaalima', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'xBxiskbiuMg' },
{ title: 'Sajdaa', artist: 'Rahat Fateh Ali Khan, Shankar Mahadevan & Richa Sharma', youtubeId: '3rPEWcY6Oww' },
{ title: 'Dam Mast Qalandar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'SKZAiWSquA0' },
{ title: 'Jee Karda', artist: 'Singh Is Kinng | Akshay Kumar, Katrina Kaif | Pritam', youtubeId: '40IlftR0R_U' },
{ title: 'Aane Wala Pal Jaane Wala Hai', artist: 'Kishore Kumar', youtubeId: 'LqXyqxroFfY' },
{ title: 'Sheila Ki Jawani', artist: 'Tees Maar Khan | Katrina Kaif', youtubeId: '6oEt-5AsWD8' },
{ title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali, Mohit Chauhan', youtubeId: 'T94PHkuydcw' },
{ title: 'Lag Jaa Gale', artist: 'Lata Mangeshkar', youtubeId: 'TFr6G5zveS8' },
{ title: 'Oops', artist: 'King', youtubeId: 'QbG-lNAPFwM' },
{ title: 'Labon Ko', artist: 'KK', youtubeId: '0OGguI0uDfE' },
{ title: 'Yeh Raaten Yeh Mausam', artist: 'Kishore Kumar & Asha Bhosle', youtubeId: 'Fh-SxTHs3-U' },
{ title: 'Main Agar Kahoon', artist: 'Sonu Nigam & Shreya Ghoshal', youtubeId: 'DAYszemgPxc' },
{ title: 'Kya Mujhe Pyar Hai', artist: 'KK', youtubeId: '0Z-00b8Vw20' },
{ title: 'Tu Jaane Na', artist: 'Atif Aslam', youtubeId: 'P8PWN1OmZOA' },
{ title: 'Bulla Ki Jaana', artist: 'Rabbi Shergill', youtubeId: 'v5M98g4L6Wc' },
{ title: 'Maula Mere Maula', artist: 'Roop Kumar Rathod', youtubeId: 'Qosb9gvzRAY' },
{ title: 'Sunn Raha Hai', artist: 'Ankit Tiwari', youtubeId: 'tQL-gx7PeBc' },
{ title: 'Love', artist: 'Lana Del Rey', youtubeId: '3-NTv0CdFCk' },
{ title: 'Pal Pal Dil Ke Paas', artist: 'Kishore Kumar', youtubeId: 'AMuRRXCuyMT' },
{ title: 'Ranjish Hi Sahi', artist: 'Ali Sethi', youtubeId: 'pba_YmWDAIU' },
{ title: 'Chura Liya Hai Tumne Jo Dil Ko', artist: 'Asha Bhosle & Mohammad Rafi', youtubeId: 'dkqU7aq82XQ' },
{ title: 'Achchi Lagti Ho', artist: 'Kuch Naa Kaho | Abhishek Bachchan & Aishwarya Rai Bachchan', youtubeId: '3FMe9RttIs0' },
{ title: 'Tera Chehra', artist: 'Arijit Singh', youtubeId: 'wExehiymGl0' },
{ title: 'Mehbooba Mehbooba', artist: 'Ajnabee | Adnan Sami | Sunidhi Chauhan', youtubeId: 'oHi0fb1Mb6o' },
{ title: 'Sach Keh Raha Hai Deewana', artist: 'KK', youtubeId: 'PizHX6Kuy1M' },
{ title: 'Nothing\'s Gonna Hurt You Baby', artist: 'Cigarettes After Sex', youtubeId: 'R2LgceqKPgw' },
{ title: 'Saans', artist: 'Shreya Ghoshal & Mohit Chauhan', youtubeId: 'VAt6TO2gdko' },
{ title: 'Jeena Jeena', artist: 'Atif Aslam', youtubeId: 'zFdi834FiZ4' },
{ title: 'Pablo', artist: 'King', youtubeId: '-Xx0xnlBVzc' },
{ title: 'Tum Tak', artist: 'Javed Ali, Pooja Vaidyanath & Kirti Sagathia', youtubeId: 'k09uvR5eUao' },
{ title: 'Sayyoni', artist: 'Junoon', youtubeId: 'tEgRrHl6IB8' },
{ title: 'Alvida', artist: 'KK', youtubeId: '40ArqHBIp2s' },
{ title: 'Dil Diyan Gallan', artist: 'Atif Aslam', youtubeId: 'SAcpESN_Fk4' },
{ title: 'Chaap Tilak', artist: 'Abida Parveen & Rahat Fateh Ali Khan', youtubeId: '7SDrjwtfKMk' },
{ title: 'Khuda Jaane', artist: 'KK & Shilpa Rao', youtubeId: 'cmMiyzascLo' },
{ title: 'Tumhein Dillagi Bhool Jani Padegi', artist: 'Nusrat Fateh Ali Khan', youtubeId: '_ilWSwh5JRM' },
{ title: 'Main Tera Hero (Shanivaar Raati)', artist: 'Main Tera Hero | Arijit Singh | Varun Dhawan', youtubeId: 'Ee_9J9lGgS0' },
{ title: 'Pehle Bhi Main', artist: 'Vishal Mishra', youtubeId: 'iAIBF2ngbWY' },
{ title: 'A&W', artist: 'Lana Del Rey', youtubeId: 'rN3G4yK1klo' },
{ title: 'Kangna (Acoustic Mix)', artist: 'Dr Zeus | Lehmber Hussainpuri | Unda Da Influence', youtubeId: 'ua_jvj9dZJQ' },
{ title: 'Touch Me', artist: 'Dhoom:2 | Abhishek Bachchan, Bipasha Basu, Uday Chopra | KK, Alisha Chinai', youtubeId: 'TWcSSDtSz0o' },
{ title: 'Aao Milo Chalo', artist: 'Shaan & Ustad Sultan Khan', youtubeId: 'Mo5tQDcs__g' },
{ title: 'Sweet', artist: 'Lana Del Rey', youtubeId: '-Fg-DcLJY4s' },
{ title: 'Husn', artist: 'Anuv Jain', youtubeId: 'gJLVTKhTnog' },
{ title: 'Cold/Mess', artist: 'Prateek Kuhad', youtubeId: 'Il7Nv270zNk' },
{ title: 'Say Yes to Heaven', artist: 'Lana Del Rey', youtubeId: 'MiAoetOXKcY' },
{ title: 'Tu Aake Dekhle', artist: 'King', youtubeId: 'E9zWVQypoSM' },
{ title: 'Ye Jo Halka Halka Suroor Hai', artist: 'Nusrat Fateh Ali Khan', youtubeId: '4rkuD3JXDvA' },
{ title: 'Halkat Jawani', artist: 'Heroine | Kareena Kapoor | Sunidhi Chauhan | Salim-Sulaiman', youtubeId: 'PzcSrkMKDdk' },
{ title: 'Baarishein', artist: 'Anuv Jain', youtubeId: 'V-2S4mZ1vP8' },
{ title: 'Tajdar-e-Haram', artist: 'Atif Aslam (Coke Studio)', youtubeId: 'hCnf8PD_GJE' },
{ title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', youtubeId: 'nyuo9-OjNNg' },
{ title: 'Chaleya', artist: 'Arijit Singh & Shilpa Rao', youtubeId: 'VAdGW7QDJiU' },
{ title: 'Aadat', artist: 'Atif Aslam', youtubeId: 'B5ouTuvgWv4' },
{ title: 'Tere Bin', artist: 'Rabbi Shergill', youtubeId: 'BGZyOpuHph0' },
{ title: 'A Thousand Years', artist: 'Christina Perri', youtubeId: 'rtOvBOTyX00' },
{ title: 'O Mere Dil Ke Chain', artist: 'Kishore Kumar', youtubeId: '9jHPhM6hVmg' },
];
