export interface Track {
  title: string;
  artist: string;
  youtubeId: string;
}

export const tracks: Track[] = [
  { title: 'O Meri Jaan', artist: 'KK', youtubeId: 'n1mqINz7g1w' },
  { title: 'Video Games', artist: 'Lana Del Rey', youtubeId: 'cE6wxDqdOV0' },
  { title: 'Tajdar-e-Haram', artist: 'Atif Aslam (Coke Studio)', youtubeId: 'hCnf8PD_GJE' },
  { title: 'Apna Bana Le', artist: 'Arijit Singh', youtubeId: 'Wv5Ac3su5r4' },
  { title: 'Nothing\'s Gonna Hurt You Baby', artist: 'Cigarettes After Sex', youtubeId: 'R2LgceqKPgw' },
  { title: 'Choo Lo', artist: 'The Local Train', youtubeId: 'sFMRqxCexDk' },
  { title: 'Zara Sa', artist: 'KK', youtubeId: 'h53N55_n-9M' },
  { title: 'Say Yes to Heaven', artist: 'Lana Del Rey', youtubeId: 'MiAoetOXKcY' },
  { title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali, Mohit Chauhan', youtubeId: 'T94PHkuydcw' },
  { title: 'Riha', artist: 'Anuv Jain', youtubeId: 'oXKWFFefWK0' },
  { title: 'Yellow', artist: 'Coldplay', youtubeId: 'yKNxeF4KMsY' },
  { title: 'Lag Jaa Gale', artist: 'Lata Mangeshkar', youtubeId: 'TFr6G5zveS8' },
  { title: 'Tera Mera Rishta', artist: 'Mustafa Zahid', youtubeId: 'XA_uBJjutgc' },
  { title: 'Husn', artist: 'Anuv Jain', youtubeId: 'gJLVTKhTnog' },
  { title: 'Pasoori', artist: 'Ali Sethi & Shae Gill', youtubeId: '5Eqb_-j3FDA' },
  { title: 'Chemtrails Over the Country Club', artist: 'Lana Del Rey', youtubeId: 'vBHild0PiTE' },
  { title: 'Dil Ibaadat', artist: 'KK', youtubeId: 'w8wZ9-2-a1M' },
  { title: 'Tu Jhoom', artist: 'Naseebo Lal & Abida Parveen', youtubeId: '7D4vNcK6D38' },
  { title: 'Mahiye Jinna Sohna', artist: 'Darshan Raval', youtubeId: 'D1G_jrSSEe4' },
  { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', youtubeId: 'nyuo9-OjNNg' },
  { title: 'Pal Pal Dil Ke Paas', artist: 'Kishore Kumar', youtubeId: 'AMuRRXCuyMT' },
  { title: 'Dheere Dheere Se Meri Zindagi Mein Aana', artist: 'Kumar Sanu & Anuradha Paudwal', youtubeId: 'Mcs2xEZ6K8o' },
  { title: 'Cold/Mess', artist: 'Prateek Kuhad', youtubeId: 'Il7Nv270zNk' },
  { title: 'Afreen Afreen', artist: 'Rahat Fateh Ali Khan & Momina Mustehsan', youtubeId: 'kw4tT7SCmaY' },
  { title: 'Satranga', artist: 'Arijit Singh', youtubeId: 'HrnrqYxYrbk' },
  { title: 'Cinnamon Girl', artist: 'Lana Del Rey', youtubeId: 'Q4yR4_W1o2s' },
  { title: 'Aankhon Mein Teri', artist: 'KK', youtubeId: 'tqmqB-4Xt9U' },
  { title: 'Tum Hi Ho', artist: 'Arijit Singh', youtubeId: 'Umqb9KENgmk' },
  { title: 'Brooklyn Baby', artist: 'Lana Del Rey', youtubeId: 'T5xcnjAG8pE' },
  { title: 'Khwaja Mere Khwaja', artist: 'A.R. Rahman', youtubeId: 'z4RvWbJlbPU' },
  { title: 'Kaho Na Kaho', artist: 'Amir Jamal', youtubeId: 'GPvCVzD70Zs' },
  { title: 'Baarishein', artist: 'Anuv Jain', youtubeId: 'V-2S4mZ1vP8' },
  { title: 'Chaleya', artist: 'Arijit Singh & Shilpa Rao', youtubeId: 'VAdGW7QDJiU' },
  { title: 'Co2', artist: 'Prateek Kuhad', youtubeId: 'U2SVCCENLjE' },
  { title: 'Teri Deewani', artist: 'Kailash Kher', youtubeId: 'zZasH6qkn8M' },
  { title: 'Sweet', artist: 'Lana Del Rey', youtubeId: '-Fg-DcLJY4s' },
  { title: 'Tu Hi Meri Shab Hai', artist: 'KK', youtubeId: 'cGNcjqXe87U' },
  { title: 'Kahani Suno 2.0', artist: 'Kaifi Khalil', youtubeId: '_X38626-o5U' },
  { title: 'Hai Junoon', artist: 'KK', youtubeId: '_hEgNwyHlAU' },
  { title: 'Another Love', artist: 'Tom Odell', youtubeId: 'MwpMEbgC7DA' },
  { title: 'Gulabi Aankhen', artist: 'Mohammad Rafi', youtubeId: '6Z3DO-OFIjQ' },
  { title: 'Aao Milo Chalo', artist: 'Shaan & Ustad Sultan Khan', youtubeId: 'Mo5tQDcs__g' },
  { title: 'K.', artist: 'Cigarettes After Sex', youtubeId: 'L4sbDxRz29Q' },
  { title: 'Agar Tum Saath Ho', artist: 'Arijit Singh & Alka Yagnik', youtubeId: 'FOA9iyxsW_A' },
  { title: 'Tainu Khabar Nahi', artist: 'Arijit Singh', youtubeId: '8zkUFoXku0Y' },
  { title: 'A&W', artist: 'Lana Del Rey', youtubeId: 'rN3G4yK1klo' },
  { title: 'Pehle Bhi Main', artist: 'Vishal Mishra', youtubeId: 'iAIBF2ngbWY' },
  { title: 'Arziyan', artist: 'Javed Ali & Kailash Kher', youtubeId: 'JA09HEGTzCU' },
  { title: 'Kaisa Ye Raaz Hai', artist: 'KK', youtubeId: 'Oyzq17sdBv0' },
  { title: 'Iraaday', artist: 'Abdul Hannan & Rakan', youtubeId: 'o6c4_1-987M' },
  { title: 'Tu Aake Dekhle', artist: 'King', youtubeId: 'E9zWVQypoSM' },
  { title: 'Love', artist: 'Lana Del Rey', youtubeId: '3-NTv0CdFCk' },
  { title: 'Ranjish Hi Sahi', artist: 'Ali Sethi', youtubeId: 'pba_YmWDAIU' },
  { title: 'Sajni', artist: 'Arijit Singh', youtubeId: 'AFTIVN8rRbI' },
  { title: 'Aftab', artist: 'The Local Train', youtubeId: '8992_b1M_w8' },
  { title: 'Maan Meri Jaan', artist: 'King', youtubeId: 'VuG7ge_8I2Y' },
  { title: 'A Thousand Years', artist: 'Christina Perri', youtubeId: 'rtOvBOTyX00' },
  { title: 'Tu Mile Dil Khile', artist: 'Kumar Sanu', youtubeId: 'nqTS7ngviwQ' },
  { title: 'Chaand Baaliyan', artist: 'Aditya A', youtubeId: 'Xi8Fabcb_MA' },
  { title: 'Ektarfa', artist: 'King', youtubeId: 'Un3r589324M' },
  { title: 'Ye Jo Halka Halka Suroor Hai', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'v0G1mK8i8eA' },
  { title: 'Aap Ki Aankhon Mein Kuch', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'K4vW8Y3636g' },
  { title: 'Khuda Jaane', artist: 'KK & Shilpa Rao', youtubeId: 'cmMiyzascLo' },
  { title: 'Heeriye', artist: 'Jasleen Royal & Arijit Singh', youtubeId: 'RLzC55ai0eo' },
  { title: 'Soni Soni', artist: 'Darshan Raval, Jonita Gandhi & Rochak Kohli', youtubeId: 'N7y9k4oW89w' },
  { title: 'Tere Sang Ishq Hua', artist: 'Arijit Singh & Neeti Mohan', youtubeId: 'p0l9X2k5G34' },
  { title: 'Labon Ko', artist: 'KK', youtubeId: 'R4z8wLp7y7o' },
  { title: 'Liggi', artist: 'Ritviz', youtubeId: 'x78j9z1W234' },
  { title: 'Tum Se Hi', artist: 'Mohit Chauhan', youtubeId: 'Cb6wuzOurPc' },
  { title: 'Zaalima', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'hhdSyBHuI8w' },
  { title: 'Bikhra', artist: 'Abdul Hannan & Rakan', youtubeId: 'c2M9gZ6x-9E' },
  { title: 'Hawayein', artist: 'Arijit Singh', youtubeId: 'cYOB941uu3Y' },
  { title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', youtubeId: 'g0eO74UmwSC' },
  { title: 'Shayad', artist: 'Arijit Singh', youtubeId: 'v0G1mK8i8eA' },
  { title: 'Tujhe Kitna Chahne Lage', artist: 'Arijit Singh', youtubeId: 'AFi16VpZ4sA' },
  { title: 'Pehli Nazar Mein', artist: 'Atif Aslam', youtubeId: 'BadB1z-9_vI' },
  { title: 'Khairiyat', artist: 'Arijit Singh', youtubeId: 'hoNb6HuAiU0' },
  { title: 'Ae Dil Hai Mushkil', artist: 'Arijit Singh', youtubeId: '6FURuLYrR_Q' },
  { title: 'Maula Mere Maula', artist: 'Roop Kumar Rathod', youtubeId: 'x78j9z1W234' },
  { title: 'Kabira (Encore)', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'jHNNMj5bNQw' },
  { title: 'Ilahi', artist: 'Arijit Singh', youtubeId: '8T6b-h418uM' },
  { title: 'Kya Mujhe Pyar Hai', artist: 'KK', youtubeId: '0Z-00b8Vw20' },
  { title: 'Kho Gaye Hum Kahan', artist: 'Jasleen Royal & Prateek Kuhad', youtubeId: 'vt4m_b3K_18' },
  { title: 'Beete Lamhein', artist: 'KK', youtubeId: 'N-n8V7k_14I' },
  { title: 'Yaaron', artist: 'KK', youtubeId: 'Vz_y8-vV_4M' },
  { title: 'Pal', artist: 'KK', youtubeId: '8_0A8Z-0_aM' },
  { title: 'Tadap Tadap', artist: 'KK', youtubeId: 'Z638626-o5U' },
  { title: 'Iktara', artist: 'Kavita Seth & Amitabh Bhattacharya', youtubeId: 'f_9E-h39L1U' },
  { title: 'Awarapan Banjarapan', artist: 'KK', youtubeId: 'x78j9z1W234' },
  { title: 'Sach Keh Raha Hai Deewana', artist: 'KK', youtubeId: 'v0G1mK8i8eA' },
  { title: 'Alag Aasmaan', artist: 'Anuv Jain', youtubeId: '8N362h-K-8g' },
  { title: 'Gul', artist: 'Anuv Jain', youtubeId: 'h-9m01A-154' },
  { title: 'Mishri', artist: 'Anuv Jain', youtubeId: 'BMb1xP0_s28' },
  { title: 'Ocean', artist: 'Anuv Jain', youtubeId: 'Py4qBkyG_1E' },
  { title: 'Kasoor', artist: 'Prateek Kuhad', youtubeId: 'BMb1xP0_s28' },
  { title: 'Tune Kaha', artist: 'Prateek Kuhad', youtubeId: 'N7y9k4oW89w' },
  { title: 'Dil Beparwah', artist: 'Prateek Kuhad & Ankur Tewari', youtubeId: 'sFMRqxCexDk' },
  { title: 'Dil Mere', artist: 'The Local Train', youtubeId: 'h-9m01A-154' },
  { title: 'Khudi', artist: 'The Local Train', youtubeId: 'a17_54K5vM4' },
  { title: 'Udd Gaye', artist: 'Ritviz', youtubeId: 'v7Y53gM4x4s' },
  { title: 'Tu Jaane Na', artist: 'Atif Aslam', youtubeId: 'P8PWN1OmZOA' },
  { title: 'Dil Diyan Gallan', artist: 'Atif Aslam', youtubeId: 'SAcpESN_Fk4' },
  { title: 'Jeene Laga Hoon', artist: 'Atif Aslam & Shreya Ghoshal', youtubeId: 'vp28_G_vK3E' },
  { title: 'Tere Sang Yaara', artist: 'Atif Aslam', youtubeId: 'v9-9d7-83K0' },
  { title: 'Aadat', artist: 'Atif Aslam', youtubeId: '8_0A8Z-0_aM' },
  { title: 'Kuch Is Tarah', artist: 'Atif Aslam', youtubeId: 'zQW64g538v0' },
  { title: 'Jeena Jeena', artist: 'Atif Aslam', youtubeId: '_156m-m27-g' },
  { title: 'Abhi Mujh Mein Kahin', artist: 'Sonu Nigam', youtubeId: 'fo9E-h39L1U' },
  { title: 'Suraj Hua Maddham', artist: 'Sonu Nigam & Alka Yagnik', youtubeId: 'L0zV_B36j7A' },
  { title: 'Main Agar Kahoon', artist: 'Sonu Nigam & Shreya Ghoshal', youtubeId: 'DAYszemgPxc' },
  { title: 'Pee Loon', artist: 'Mohit Chauhan', youtubeId: 'Z95W62S6q1I' },
  { title: 'Phir Se Ud Chala', artist: 'Mohit Chauhan', youtubeId: '27yW6zM6xEU' },
  { title: 'Saans', artist: 'Shreya Ghoshal & Mohit Chauhan', youtubeId: '2p2aG3m4K9o' },
  { title: 'Tera Zikr', artist: 'Darshan Raval', youtubeId: '_156m-m27-g' },
  { title: 'Bhula Dunga', artist: 'Darshan Raval', youtubeId: 'a17_54K5vM4' },
  { title: 'Hawa Banke', artist: 'Darshan Raval', youtubeId: 'v0G1mK8i8eA' },
  { title: 'Ek Tarfa', artist: 'Darshan Raval', youtubeId: 'Un3r589324M' },
  { title: 'Mehrama', artist: 'Darshan Raval & Antara Mitra', youtubeId: 'J0Xg4rU_3-c' },
  { title: 'Oops', artist: 'King', youtubeId: 'm499qK-290c' },
  { title: 'Pablo', artist: 'King', youtubeId: 'a17_54K5vM4' },
  { title: 'Din Shagna Da', artist: 'Jasleen Royal', youtubeId: 'x78j9z1W234' },
  { title: 'Tera Ban Jaunga', artist: 'Akhil Sachdeva & Tulsi Kumar', youtubeId: 'Bq_q41V8hMo' },
  { title: 'Kaun Tujhe', artist: 'Palak Muchhal', youtubeId: 'atVof3pjT-I' },
  { title: 'Raanjhanaa', artist: 'A.R. Rahman & Jaswinder Singh', youtubeId: 'l8zZ-8c2U3g' },
  { title: 'Tum Tak', artist: 'Javed Ali, Pooja Vaidyanath & Kirti Sagathia', youtubeId: 'vM3R4gH1w_o' },
  { title: 'Subhanallah', artist: 'Sreerama Chandra & Shilpa Rao', youtubeId: 'a17_54K5vM4' },
  { title: 'Bolna', artist: 'Arijit Singh & Asees Kaur', youtubeId: 'AJtDXIazrMo' },
  { title: 'Hamsafar', artist: 'Akhil Sachdeva', youtubeId: 'R2LgceqKPgw' },
  { title: 'Naina', artist: 'Arijit Singh', youtubeId: 'V4sK4X-937M' },
  { title: 'Samjhawan', artist: 'Arijit Singh & Shreya Ghoshal', youtubeId: 'H2f7MZyQZtA' },
  { title: 'Galliyan', artist: 'Ankit Tiwari', youtubeId: 'gS822s_T48g' },
  { title: 'Sunn Raha Hai', artist: 'Ankit Tiwari', youtubeId: 'rtOvBOTyX00' },
  { title: 'Tera Chehra', artist: 'Arijit Singh', youtubeId: 'vP4882x-04M' },
  { title: 'Yeh Raaten Yeh Mausam', artist: 'Kishore Kumar & Asha Bhosle', youtubeId: 'm499qK-290c' },
  { title: 'Chura Liya Hai Tumne Jo Dil Ko', artist: 'Asha Bhosle & Mohammad Rafi', youtubeId: 'sK7riqg254H' },
  { title: 'Kora Kagaz Tha Yeh Man Mera', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'L0zV_B36j7A' },
  { title: 'O Mere Dil Ke Chain', artist: 'Kishore Kumar', youtubeId: 'g0eO74UmwSC' },
  { title: 'Roop Tera Mastana', artist: 'Kishore Kumar', youtubeId: 'fo9E-h39L1U' },
  { title: 'Kya Hua Tera Wada', artist: 'Mohammad Rafi', youtubeId: 'Cb6wuzOurPc' },
  { title: 'Tujhse Naraz Nahin Zindagi', artist: 'Lata Mangeshkar / Anup Ghoshal', youtubeId: 'AFi16VpZ4sA' },
  { title: 'Tere Bina Zindagi Se', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'bd9D-iZ17Yk' },
  { title: 'Pyar Deewana Hota Hai', artist: 'Kishore Kumar', youtubeId: 'vBHild0PiTE' },
  { title: 'Rimjhim Gire Sawan', artist: 'Kishore Kumar / Lata Mangeshkar', youtubeId: 'ND1s5lJydHw' },
  { title: 'Aane Wala Pal Jaane Wala Hai', artist: 'Kishore Kumar', youtubeId: 'hr391-J587k' },
  { title: 'Chhookar Mere Manko', artist: 'Kishore Kumar', youtubeId: 'RoL5i32O4rM' },
  { title: 'Kabhi Kabhie Mere Dil Mein', artist: 'Mukesh', youtubeId: '0p1y0J2lM_w' },
  { title: 'Kana Yaari', artist: 'Kaifi Khalil, Eva B & Wahab Bugti', youtubeId: 'zQW64g538v0' },
  { title: 'Maeri', artist: 'Euphoria', youtubeId: 'p0l9X2k5G34' },
  { title: 'Sayyoni', artist: 'Junoon', youtubeId: 'MwpMEbgC7DA' },
  { title: 'Bulla Ki Jaana', artist: 'Rabbi Shergill', youtubeId: 'v5M98g4L6Wc' },
  { title: 'Chaap Tilak', artist: 'Abida Parveen & Rahat Fateh Ali Khan', youtubeId: 'FN4x5m3E-8A' },
  { title: 'Aaqa', artist: 'Abida Parveen & Ali Sethi', youtubeId: '3gQozRwTFzI' },
  { title: 'Man Kunto Maula', artist: 'Javed Ali & Shadab Faridi', youtubeId: 'ND1s5lJydHw' },
  { title: 'Rashke Qamar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'hhdSyBHuI8w' },
  { title: 'Tumhein Dillagi Bhool Jani Padegi', artist: 'Nusrat Fateh Ali Khan', youtubeId: '0p1y0J2lM_w' },
  { title: 'Dam Mast Qalandar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'bd9D-iZ17Yk' },
  { title: 'Sanwaroo', artist: 'Sabri Brothers', youtubeId: '27yW6zM6xEU' },
  { title: 'Bhar Do Jholi Meri', artist: 'Sabri Brothers', youtubeId: '2p2aG3m4K9o' },
  { title: 'Javeda Zindagi / Tose Naina Lage', artist: 'Kshitij Tarey & Shilpa Rao', youtubeId: 'A66TYFzyJtU' },
  { title: 'Tere Bin', artist: 'Rabbi Shergill', youtubeId: 'VuG7ge_8BKw' },
  { title: 'Sajdaa', artist: 'Rahat Fateh Ali Khan, Shankar Mahadevan & Richa Sharma', youtubeId: 'k3g_WjVCs54' },
  { title: 'O Re Piya', artist: 'Rahat Fateh Ali Khan', youtubeId: 'L8zZ-8c2U3g' },
  { title: 'Yaar Boliya', artist: 'Kailash Kher', youtubeId: 'vP4882x-04M' },
  { title: 'Saiyyan', artist: 'Kailash Kher', youtubeId: 'dCmp56tSSNc' },
  { title: 'Piya Ghar Aavenge', artist: 'Kailash Kher', youtubeId: 'T5xbkj3fqHM' },
  { title: 'Alvida', artist: 'KK', youtubeId: 'Un3r589324M' },
];
