export interface Track {
  title: string;
  artist: string;
  youtubeId: string;
}

export const tracks: Track[] = [
  { title: 'O Meri Jaan', artist: 'KK', youtubeId: 'n1mqINz7g1w' },
  { title: 'Video Games', artist: 'Lana Del Rey', youtubeId: 'cE6wxDqdOV0' },
  { title: 'Tajdar-e-Haram', artist: 'Atif Aslam (Coke Studio)', youtubeId: 'hCnf8PD_GJE' },
  { title: 'Nothing\'s Gonna Hurt You Baby', artist: 'Cigarettes After Sex', youtubeId: 'R2LgceqKPgw' },
  { title: 'Choo Lo', artist: 'The Local Train', youtubeId: 'sFMRqxCexDk' },
  { title: 'Zara Sa', artist: 'KK', youtubeId: 'h53N55_n-9M' },
  { title: 'Say Yes to Heaven', artist: 'Lana Del Rey', youtubeId: 'MiAoetOXKcY' },
  { title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali, Mohit Chauhan', youtubeId: 'T94PHkuydcw' },
  { title: 'Riha', artist: 'Anuv Jain', youtubeId: 'oXKWFFefWK0' },
  { title: 'Yellow', artist: 'Coldplay', youtubeId: 'yKNxeF4KMsY' },
  { title: 'Lag Jaa Gale', artist: 'Lata Mangeshkar', youtubeId: 'TFr6G5zveS8' },
  { title: 'Tera Mera Rishta', artist: 'Mustafa Zahid', youtubeId: 'XA_uBJjutgc' },
  { title: 'Husn', artist: 'Anuv Jain', youtubeId: 'gJLVTKhTnog' },
  { title: 'Pasoori', artist: 'Ali Sethi & Shae Gill', youtubeId: '5Eqb_-j3FDA' },
  { title: 'Chemtrails Over the Country Club', artist: 'Lana Del Rey', youtubeId: 'vBHild0PiTE' },
  { title: 'Dil Ibaadat', artist: 'KK', youtubeId: 'w8wZ9-2-a1M' },
  { title: 'Tu Jhoom', artist: 'Naseebo Lal & Abida Parveen', youtubeId: '7D4vNcK6D38' },
  { title: 'Mahiye Jinna Sohna', artist: 'Darshan Raval', youtubeId: 'D1G_jrSSEe4' },
  { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', youtubeId: 'nyuo9-OjNNg' },
  { title: 'Pal Pal Dil Ke Paas', artist: 'Kishore Kumar', youtubeId: 'AMuRRXCuyMT' },
  { title: 'Cold/Mess', artist: 'Prateek Kuhad', youtubeId: 'Il7Nv270zNk' },
  { title: 'Afreen Afreen', artist: 'Rahat Fateh Ali Khan & Momina Mustehsan', youtubeId: 'kw4tT7SCmaY' },
  { title: 'Satranga', artist: 'Arijit Singh', youtubeId: 'HrnrqYxYrbk' },
  { title: 'Cinnamon Girl', artist: 'Lana Del Rey', youtubeId: 'Q4yR4_W1o2s' },
  { title: 'Aankhon Mein Teri', artist: 'KK', youtubeId: 'tqmqB-4Xt9U' },
  { title: 'Tum Hi Ho', artist: 'Arijit Singh', youtubeId: 'Umqb9KENgmk' },
  { title: 'Brooklyn Baby', artist: 'Lana Del Rey', youtubeId: 'T5xcnjAG8pE' },
  { title: 'Khwaja Mere Khwaja', artist: 'A.R. Rahman', youtubeId: 'z4RvWbJlbPU' },
  { title: 'Kaho Na Kaho', artist: 'Amir Jamal', youtubeId: 'GPvCVzD70Zs' },
  { title: 'Baarishein', artist: 'Anuv Jain', youtubeId: 'V-2S4mZ1vP8' },
  { title: 'Chaleya', artist: 'Arijit Singh & Shilpa Rao', youtubeId: 'VAdGW7QDJiU' },
  { title: 'Co2', artist: 'Prateek Kuhad', youtubeId: 'U2SVCCENLjE' },
  { title: 'Teri Deewani', artist: 'Kailash Kher', youtubeId: 'zZasH6qkn8M' },
  { title: 'Sweet', artist: 'Lana Del Rey', youtubeId: '-Fg-DcLJY4s' },
  { title: 'Tu Hi Meri Shab Hai', artist: 'KK', youtubeId: 'cGNcjqXe87U' },
  { title: 'Kahani Suno 2.0', artist: 'Kaifi Khalil', youtubeId: '_X38626-o5U' },
  { title: 'Hai Junoon', artist: 'KK', youtubeId: '_hEgNwyHlAU' },
  { title: 'Another Love', artist: 'Tom Odell', youtubeId: 'MwpMEbgC7DA' },
  { title: 'Gulabi Aankhen', artist: 'Mohammad Rafi', youtubeId: '6Z3DO-OFIjQ' },
  { title: 'Aao Milo Chalo', artist: 'Shaan & Ustad Sultan Khan', youtubeId: 'Mo5tQDcs__g' },
  { title: 'K.', artist: 'Cigarettes After Sex', youtubeId: 'L4sbDxRz29Q' },
  { title: 'Agar Tum Saath Ho', artist: 'Arijit Singh & Alka Yagnik', youtubeId: 'FOA9iyxsW_A' },
  { title: 'Tainu Khabar Nahi', artist: 'Arijit Singh', youtubeId: '8zkUFoXku0Y' },
  { title: 'A&W', artist: 'Lana Del Rey', youtubeId: 'rN3G4yK1klo' },
  { title: 'Pehle Bhi Main', artist: 'Vishal Mishra', youtubeId: 'iAIBF2ngbWY' },
  { title: 'Arziyan', artist: 'Javed Ali & Kailash Kher', youtubeId: 'JA09HEGTzCU' },
  { title: 'Kaisa Ye Raaz Hai', artist: 'KK', youtubeId: 'Oyzq17sdBv0' },
  { title: 'Iraaday', artist: 'Abdul Hannan & Rakan', youtubeId: 'o6c4_1-987M' },
  { title: 'Tu Aake Dekhle', artist: 'King', youtubeId: 'E9zWVQypoSM' },
  { title: 'Love', artist: 'Lana Del Rey', youtubeId: '3-NTv0CdFCk' },
  { title: 'Ranjish Hi Sahi', artist: 'Ali Sethi', youtubeId: 'pba_YmWDAIU' },
  { title: 'Sajni', artist: 'Arijit Singh', youtubeId: 'AFTIVN8rRbI' },
  { title: 'Aftab', artist: 'The Local Train', youtubeId: '8992_b1M_w8' },
  { title: 'Maan Meri Jaan', artist: 'King', youtubeId: 'VuG7ge_8I2Y' },
  { title: 'A Thousand Years', artist: 'Christina Perri', youtubeId: 'rtOvBOTyX00' },
  { title: 'Tu Mile Dil Khile', artist: 'Kumar Sanu', youtubeId: 'nqTS7ngviwQ' },
  { title: 'Chaand Baaliyan', artist: 'Aditya A', youtubeId: 'Xi8Fabcb_MA' },
  { title: 'Ektarfa', artist: 'King', youtubeId: '4IAnSQKUC5Q' },
  { title: 'Ye Jo Halka Halka Suroor Hai', artist: 'Nusrat Fateh Ali Khan', youtubeId: '4rkuD3JXDvA' },
  { title: 'Aap Ki Aankhon Mein Kuch', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'K4vW8Y3636g' },
  { title: 'Khuda Jaane', artist: 'KK & Shilpa Rao', youtubeId: 'cmMiyzascLo' },
  { title: 'Heeriye', artist: 'Jasleen Royal & Arijit Singh', youtubeId: 'RLzC55ai0eo' },
  { title: 'Soni Soni', artist: 'Darshan Raval, Jonita Gandhi & Rochak Kohli', youtubeId: 'y8vwzo8AgXU' },
  { title: 'Tere Sang Ishq Hua', artist: 'Arijit Singh & Neeti Mohan', youtubeId: '0qgMcrGuyQc' },
  { title: 'Labon Ko', artist: 'KK', youtubeId: '0OGguI0uDfE' },
  { title: 'Liggi', artist: 'Ritviz', youtubeId: '6BYIKEH0RCQ' },
  { title: 'Tum Se Hi', artist: 'Mohit Chauhan', youtubeId: 'Cb6wuzOurPc' },
  { title: 'Zaalima', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'xBxiskbiuMg' },
  { title: 'Bikhra', artist: 'Abdul Hannan & Rakan', youtubeId: 'c2M9gZ6x-9E' },
  { title: 'Hawayein', artist: 'Arijit Singh', youtubeId: 'cYOB941uu3Y' },
  { title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', youtubeId: 'g0eO74UmRBs' },
  { title: 'Shayad', artist: 'Arijit Singh', youtubeId: 'Aq1o2C0DL-s' },
  { title: 'Tujhe Kitna Chahne Lage', artist: 'Arijit Singh', youtubeId: 'AgX2II9si7w' },
  { title: 'Pehli Nazar Mein', artist: 'Atif Aslam', youtubeId: 'BadB1z-9_vI' },
  { title: 'Khairiyat', artist: 'Arijit Singh', youtubeId: 'hoNb6HuAiU0' },
  { title: 'Ae Dil Hai Mushkil', artist: 'Arijit Singh', youtubeId: '6FURuLYrR_Q' },
  { title: 'Maula Mere Maula', artist: 'Roop Kumar Rathod', youtubeId: 'Qosb9gvzRAY' },
  { title: 'Kabira (Encore)', artist: 'Arijit Singh & Harshdeep Kaur', youtubeId: 'jHNNMj5bNQw' },
  { title: 'Ilahi', artist: 'Arijit Singh', youtubeId: '8T6b-h418uM' },
  { title: 'Kya Mujhe Pyar Hai', artist: 'KK', youtubeId: '0Z-00b8Vw20' },
  { title: 'Kho Gaye Hum Kahan', artist: 'Jasleen Royal & Prateek Kuhad', youtubeId: 'vt4m_b3K_18' },
  { title: 'Beete Lamhein', artist: 'KK', youtubeId: 'N-n8V7k_14I' },
  { title: 'Yaaron', artist: 'KK', youtubeId: 'Vz_y8-vV_4M' },
  { title: 'Pal', artist: 'KK', youtubeId: 'gM7yO9yRsiI' },
  { title: 'Tadap Tadap', artist: 'KK', youtubeId: 'Z638626-o5U' },
  { title: 'Iktara', artist: 'Kavita Seth & Amitabh Bhattacharya', youtubeId: 'f_9E-h39L1U' },
  { title: 'Awarapan Banjarapan', artist: 'KK', youtubeId: 'zHgnRLWe_GE' },
  { title: 'Sach Keh Raha Hai Deewana', artist: 'KK', youtubeId: 'PizHX6Kuy1M' },
  { title: 'Alag Aasmaan', artist: 'Anuv Jain', youtubeId: '8N362h-K-8g' },
  { title: 'Gul', artist: 'Anuv Jain', youtubeId: 'SmaY7RfBgas' },
  { title: 'Mishri', artist: 'Anuv Jain', youtubeId: '0P3Gt-60yLc' },
  { title: 'Ocean', artist: 'Anuv Jain', youtubeId: 'RpHUIUslYv0' },
  { title: 'Kasoor', artist: 'Prateek Kuhad', youtubeId: 'BmUe3-sfr7E' },
  { title: 'Tune Kaha', artist: 'Prateek Kuhad', youtubeId: 'miXdVbIm5BY' },
  { title: 'Dil Beparwah', artist: 'Prateek Kuhad & Ankur Tewari', youtubeId: 'NYyA9Ks3TKk' },
  { title: 'Dil Mere', artist: 'The Local Train', youtubeId: 'qLCLvzTGFVM' },
  { title: 'Khudi', artist: 'The Local Train', youtubeId: '9LjKAt6SkdQ' },
  { title: 'Udd Gaye', artist: 'Ritviz', youtubeId: 'v2-9rIL_f4w' },
  { title: 'Tu Jaane Na', artist: 'Atif Aslam', youtubeId: 'P8PWN1OmZOA' },
  { title: 'Dil Diyan Gallan', artist: 'Atif Aslam', youtubeId: 'SAcpESN_Fk4' },
  { title: 'Jeene Laga Hoon', artist: 'Atif Aslam & Shreya Ghoshal', youtubeId: 'vp28_G_vK3E' },
  { title: 'Tere Sang Yaara', artist: 'Atif Aslam', youtubeId: 'v9-9d7-83K0' },
  { title: 'Aadat', artist: 'Atif Aslam', youtubeId: 'B5ouTuvgWv4' },
  { title: 'Kuch Is Tarah', artist: 'Atif Aslam', youtubeId: 'E74V-X9AtAg' },
  { title: 'Jeena Jeena', artist: 'Atif Aslam', youtubeId: 'zFdi834FiZ4' },
  { title: 'Abhi Mujh Mein Kahin', artist: 'Sonu Nigam', youtubeId: 'AdY_KpBmi6k' },
  { title: 'Suraj Hua Maddham', artist: 'Sonu Nigam & Alka Yagnik', youtubeId: 'L0zKs8i7Nc8' },
  { title: 'Main Agar Kahoon', artist: 'Sonu Nigam & Shreya Ghoshal', youtubeId: 'DAYszemgPxc' },
  { title: 'Pee Loon', artist: 'Mohit Chauhan', youtubeId: 'Z95W62S6q1I' },
  { title: 'Phir Se Ud Chala', artist: 'Mohit Chauhan', youtubeId: 'GyZyndDUWFs' },
  { title: 'Saans', artist: 'Shreya Ghoshal & Mohit Chauhan', youtubeId: 'VAt6TO2gdko' },
  { title: 'Tera Zikr', artist: 'Darshan Raval', youtubeId: 'eK0IIyBlYew' },
  { title: 'Bhula Dunga', artist: 'Darshan Raval', youtubeId: 'f5ANP2-tKjs' },
  { title: 'Hawa Banke', artist: 'Darshan Raval', youtubeId: 'QCXaa1mEUK0' },
  { title: 'Ek Tarfa', artist: 'Darshan Raval', youtubeId: 'fIip0BH6z7I' },
  { title: 'Mehrama', artist: 'Darshan Raval & Antara Mitra', youtubeId: 'HYUpNJJELeE' },
  { title: 'Oops', artist: 'King', youtubeId: 'QbG-lNAPFwM' },
  { title: 'Pablo', artist: 'King', youtubeId: '-Xx0xnlBVzc' },
  { title: 'Din Shagna Da', artist: 'Jasleen Royal', youtubeId: 'ptMw5llgfOs' },
  { title: 'Tera Ban Jaunga', artist: 'Akhil Sachdeva & Tulsi Kumar', youtubeId: 'Bq_q41V8hMo' },
  { title: 'Kaun Tujhe', artist: 'Palak Muchhal', youtubeId: 'atVof3pjT-I' },
  { title: 'Raanjhanaa', artist: 'A.R. Rahman & Jaswinder Singh', youtubeId: 'l8zZ-8c2U3g' },
  { title: 'Tum Tak', artist: 'Javed Ali, Pooja Vaidyanath & Kirti Sagathia', youtubeId: 'k09uvR5eUao' },
  { title: 'Subhanallah', artist: 'Sreerama Chandra & Shilpa Rao', youtubeId: 'QYO6AlxiRE4' },
  { title: 'Bolna', artist: 'Arijit Singh & Asees Kaur', youtubeId: 'AJtDXIazrMo' },
  { title: 'Hamsafar', artist: 'Akhil Sachdeva', youtubeId: 'jIqRbFQl-ds' },
  { title: 'Naina', artist: 'Arijit Singh', youtubeId: 'yXbeYaVQ8JY' },
  { title: 'Samjhawan', artist: 'Arijit Singh & Shreya Ghoshal', youtubeId: 'H2f7MZyQZtA' },
  { title: 'Galliyan', artist: 'Ankit Tiwari', youtubeId: 'FxAG_11PzCk' },
  { title: 'Sunn Raha Hai', artist: 'Ankit Tiwari', youtubeId: 'tQL-gx7PeBc' },
  { title: 'Tera Chehra', artist: 'Arijit Singh', youtubeId: 'wExehiymGl0' },
  { title: 'Yeh Raaten Yeh Mausam', artist: 'Kishore Kumar & Asha Bhosle', youtubeId: 'Fh-SxTHs3-U' },
  { title: 'Chura Liya Hai Tumne Jo Dil Ko', artist: 'Asha Bhosle & Mohammad Rafi', youtubeId: 'dkqU7aq82XQ' },
  { title: 'Kora Kagaz Tha Yeh Man Mera', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: 'IJgRm_NQs8A' },
  { title: 'O Mere Dil Ke Chain', artist: 'Kishore Kumar', youtubeId: '9jHPhM6hVmg' },
  { title: 'Roop Tera Mastana', artist: 'Kishore Kumar', youtubeId: 'o7Jnp949e2Y' },
  { title: 'Kya Hua Tera Wada', artist: 'Mohammad Rafi', youtubeId: 'W6dKaCV-mJQ' },
  { title: 'Tujhse Naraz Nahin Zindagi', artist: 'Lata Mangeshkar / Anup Ghoshal', youtubeId: 'K1qnkWTn56w' },
  { title: 'Tere Bina Zindagi Se', artist: 'Kishore Kumar & Lata Mangeshkar', youtubeId: '8-HnmVg0-O8' },
  { title: 'Pyar Deewana Hota Hai', artist: 'Kishore Kumar', youtubeId: 'WHd3NuhxrBM' },
  { title: 'Rimjhim Gire Sawan', artist: 'Kishore Kumar / Lata Mangeshkar', youtubeId: 'JQoSSJDZxOo' },
  { title: 'Aane Wala Pal Jaane Wala Hai', artist: 'Kishore Kumar', youtubeId: 'LqXyqxroFfY' },
  { title: 'Chhookar Mere Manko', artist: 'Kishore Kumar', youtubeId: 'BOLYNw3x1lE' },
  { title: 'Kabhi Kabhie Mere Dil Mein', artist: 'Mukesh', youtubeId: 'BB6KvXQx090' },
  { title: 'Kana Yaari', artist: 'Kaifi Khalil, Eva B & Wahab Bugti', youtubeId: '0oEsLkwE3g8' },
  { title: 'Maeri', artist: 'Euphoria', youtubeId: 'MGMh7kYzNqo' },
  { title: 'Sayyoni', artist: 'Junoon', youtubeId: 'tEgRrHl6IB8' },
  { title: 'Bulla Ki Jaana', artist: 'Rabbi Shergill', youtubeId: 'v5M98g4L6Wc' },
  { title: 'Chaap Tilak', artist: 'Abida Parveen & Rahat Fateh Ali Khan', youtubeId: '7SDrjwtfKMk' },
  { title: 'Aaqa', artist: 'Abida Parveen & Ali Sethi', youtubeId: 'LekqDjknArc' },
  { title: 'Man Kunto Maula', artist: 'Javed Ali & Shadab Faridi', youtubeId: '-Dby8p6mZhY' },
  { title: 'Rashke Qamar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'gY01irEl8Eo' },
  { title: 'Tumhein Dillagi Bhool Jani Padegi', artist: 'Nusrat Fateh Ali Khan', youtubeId: '_ilWSwh5JRM' },
  { title: 'Dam Mast Qalandar', artist: 'Nusrat Fateh Ali Khan', youtubeId: 'SKZAiWSquA0' },
  { title: 'Bhar Do Jholi Meri', artist: 'Sabri Brothers', youtubeId: '55lmaGp_Uek' },
  { title: 'Javeda Zindagi / Tose Naina Lage', artist: 'Kshitij Tarey & Shilpa Rao', youtubeId: 'wpka0Q8hlXc' },
  { title: 'Tere Bin', artist: 'Rabbi Shergill', youtubeId: 'BGZyOpuHph0' },
  { title: 'Sajdaa', artist: 'Rahat Fateh Ali Khan, Shankar Mahadevan & Richa Sharma', youtubeId: '3rPEWcY6Oww' },
  { title: 'O Re Piya', artist: 'Rahat Fateh Ali Khan', youtubeId: 'iv7lcUkFVSc' },
  { title: 'Saiyyan', artist: 'Kailash Kher', youtubeId: 'TuUVVKVdZm4' },
  { title: 'Piya Ghar Aavenge', artist: 'Kailash Kher', youtubeId: 'zgJPTTiCK2E' },
  { title: 'Alvida', artist: 'KK', youtubeId: '40ArqHBIp2s' },
];
